eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8769
  
spring:
  application:
    name: service-zuul # 服务名为service-zuul

zuul:
  routes:
    api-a:
      path: /api-b/**
      serviceId: service-feign #以/api-a/ 开头的请求都转发给service-ribbon服务；
                               #以/api-b/开头的请求都转发给service-feign服务
